log-level: "info"
dir: "{{.InterfaceDir}}/mocks"
pkgname: "mocks"
structname: "Mock{{.InterfaceName}}"
filename: "mock_{{.InterfaceName | snakecase}}.go"
template: testify

packages:
  github.com/shellhub-io/shellhub/ssh/web:
    interfaces:
      Socket:
