// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewBackend creates a new instance of Backend. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBackend(t interface {
	mock.TestingT
	Cleanup(func())
}) *Backend {
	mock := &Backend{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Backend is an autogenerated mock type for the Backend type
type Backend struct {
	mock.Mock
}

type Backend_Expecter struct {
	mock *mock.Mock
}

func (_m *Backend) EXPECT() *Backend_Expecter {
	return &Backend_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type Backend
func (_mock *Backend) Get(key string) string {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Backend_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type Backend_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key string
func (_e *Backend_Expecter) Get(key any) *Backend_Get_Call {
	return &Backend_Get_Call{Call: _e.mock.On("Get", key)}
}

func (_c *Backend_Get_Call) Run(run func(key string)) *Backend_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Backend_Get_Call) Return(s string) *Backend_Get_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Backend_Get_Call) RunAndReturn(run func(key string) string) *Backend_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Process provides a mock function for the type Backend
func (_mock *Backend) Process(prefix string, spec interface{}) error {
	ret := _mock.Called(prefix, spec)

	if len(ret) == 0 {
		panic("no return value specified for Process")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, interface{}) error); ok {
		r0 = returnFunc(prefix, spec)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Backend_Process_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Process'
type Backend_Process_Call struct {
	*mock.Call
}

// Process is a helper method to define mock.On call
//   - prefix string
//   - spec interface{}
func (_e *Backend_Expecter) Process(prefix any, spec any) *Backend_Process_Call {
	return &Backend_Process_Call{Call: _e.mock.On("Process", prefix, spec)}
}

func (_c *Backend_Process_Call) Run(run func(prefix string, spec interface{})) *Backend_Process_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Backend_Process_Call) Return(err error) *Backend_Process_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Backend_Process_Call) RunAndReturn(run func(prefix string, spec interface{}) error) *Backend_Process_Call {
	_c.Call.Return(run)
	return _c
}
