description: Namespace's settings.
type: object
properties:
  session_record:
    description: The session records define when the namespace should save or not record a session. This can be used to check logged activity when connecting to a device.
    type: boolean
    example: true
  connection_announcement:
    description: A connection announcement is a custom string written during a session when a connection is established on a device within the namespace.
    type: string
    minLength: 0
    maxLength: 4096
    format: alphanumunicode
    example: my awesome connection announcement
  allow_password:
    description: Allow password authentication at namespace level
    type: boolean
    example: true
  allow_public_key:
    description: Allow public key authentication at namespace level
    type: boolean
    example: true
  allow_root:
    description: Allow root user login at namespace level
    type: boolean
    example: true
  allow_empty_passwords:
    description: Allow empty passwords at namespace level
    type: boolean
    example: false
  allow_tty:
    description: Allow TTY allocation at namespace level
    type: boolean
    example: true
  allow_tcp_forwarding:
    description: Allow TCP port forwarding at namespace level
    type: boolean
    example: true
  allow_web_endpoints:
    description: Allow web endpoints access via HTTP proxy at namespace level
    type: boolean
    example: true
  allow_sftp:
    description: Allow SFTP subsystem at namespace level
    type: boolean
    example: true
  allow_agent_forwarding:
    description: Allow SSH agent forwarding at namespace level
    type: boolean
    example: false
required: 
  - session_record
  - connection_announcement
  - allow_password
  - allow_public_key
