version: "2"
    
issues:
  uniq-by-line: true

output:
  formats:
    text:
      print-issued-lines: true
      print-linter-name: true
      colors: true

linters:
  enable:
    - gofmt
    - revive
    - gosimple
    - govet
    - ineffassign
    - copyloopvar
    - staticcheck
    - unconvert
    - unused
    - misspell
    - goimports
    - typecheck
    - errcheck
    - whitespace
    - depguard
    - stylecheck
    - nlreturn
    - nilerr
    - gosec
  settings:
    staticcheck:
      checks: ["all", "-SA1029"]
    depguard:
      rules:
        all:
          deny:
            - pkg: io/ioutil
              desc: 'io/ioutil package has been deprecated'
            - pkg: github.com/google/uuid
              desc: "Uuid generation is only allowed using 'github.com/shellhub-io/shellhub/pkg/uuid'"
            - pkg: github.com/dgrijalva/jwt-go
              desc: "dgrijalva/jwt-go is deprecated please use 'github.com/golang-jwt/jwt'"
    whitespace:
      multi-if: true
      multi-func: true
    govet:
      disable:
        - composites
