version: "2"

output:
  formats:
    text:
      print-issued-lines: true
      print-linter-name: true

issues:
  uniq-by-line: true

formatters:
  enable:
    - gofumpt
    - goimports

linters:
  disable:
    - errcheck
  enable:
    - revive
    - govet
    - ineffassign
    - copyloopvar
    - staticcheck
    - unconvert
    - unused
    - misspell
    - whitespace
    - depguard
    - nlreturn
    - nilerr
    - gosec

  settings:
    gosec:
      excludes:
        - G104
        - G301
        - G302
        - G304
    revive:
      severity: warning
    staticcheck:
      checks: ["all", "-SA1029", "-ST1020", "-ST1021", "-ST1022", "-ST1000", "-QF1008"]
    depguard:
      rules:
        all:
          deny:
            - pkg: io/ioutil
              desc: 'io/ioutil package has been deprecated'
            - pkg: github.com/google/uuid
              desc: "Uuid generation is only allowed using 'github.com/shellhub-io/shellhub/pkg/uuid'"
            - pkg: github.com/dgrijalva/jwt-go
              desc: "dgrijalva/jwt-go is deprecated please use 'github.com/golang-jwt/jwt'"
    whitespace:
      multi-if: true
      multi-func: true
    govet:
      disable:
        - composites
