services:
  server:
    restart: on-failure:3
    healthcheck:
      interval: 5s
      retries: 20
    environment:
      - SHELLHUB_OPENAPI_VALIDATION=strict
      - SHELLHUB_OPENAPI_SCHEMA=file:///etc/shellhub/openapi.json
      - SHELLHUB_LOG_FORMAT=text
    volumes:
      - ./openapi/static/openapi.json:/etc/shellhub/openapi.json:ro
  gateway:
    restart: on-failure:3
    healthcheck:
      interval: 5s
      retries: 20
  ui:
    restart: on-failure:3
    healthcheck:
      interval: 5s
      retries: 20
