services:
  mongo:
    image: mongo:4.4.29
    restart: unless-stopped
    healthcheck:
      test: 'test $$(echo "rs.initiate({ _id: ''rs'', members: [ { _id: 0, host: ''mongo:27017'' } ] }).ok || rs.status().ok" | mongo --quiet) -eq 1'
      interval: 30s
      start_period: 10s
    command: ["--replSet", "rs", "--bind_ip_all"]
    networks:
      - shellhub
  api:
    depends_on:
      mongo:
        condition: service_healthy
