version: "3.7"

services:
  server:
    image: server:test
    pull_policy: never
    restart: on-failure:3
    healthcheck:
      interval: 5s
      start_period: 10s
      retries: 20
    ports: []
    environment:
      - SHELLHUB_OPENAPI_VALIDATION=strict
      - SHELLHUB_OPENAPI_SCHEMA=file:///etc/shellhub/openapi.json
      - SHELLHUB_LOG_FORMAT=text
    volumes:
      - ./openapi/static/openapi.json:/etc/shellhub/openapi.json:ro
  gateway:
    image: gateway:test
    pull_policy: never
    restart: on-failure:3
    healthcheck:
      interval: 5s
      start_period: 10s
      retries: 20
    ports: []
  ui:
    image: ui:test
    pull_policy: never
    restart: on-failure:3
    healthcheck:
      interval: 5s
      start_period: 10s
      retries: 20
