services:
  server:
    restart: on-failure:3
    healthcheck:
      interval: 5s
      retries: 20
  gateway:
    restart: on-failure:3
    healthcheck:
      interval: 5s
      retries: 20
  redis:
    image: valkey/valkey:9.1-alpine
  ui:
    restart: on-failure:3
    healthcheck:
      interval: 5s
      retries: 20
