global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'shellhub-ssh'
    static_configs:
      - targets: ['ssh:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s
