// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/shellhub-io/shellhub/api/store"
	"github.com/shellhub-io/shellhub/pkg/api/query"
	"github.com/shellhub-io/shellhub/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// NewQueryOptions creates a new instance of QueryOptions. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQueryOptions(t interface {
	mock.TestingT
	Cleanup(func())
}) *QueryOptions {
	mock := &QueryOptions{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// QueryOptions is an autogenerated mock type for the QueryOptions type
type QueryOptions struct {
	mock.Mock
}

type QueryOptions_Expecter struct {
	mock *mock.Mock
}

func (_m *QueryOptions) EXPECT() *QueryOptions_Expecter {
	return &QueryOptions_Expecter{mock: &_m.Mock}
}

// InNamespace provides a mock function for the type QueryOptions
func (_mock *QueryOptions) InNamespace(tenantID string) store.QueryOption {
	ret := _mock.Called(tenantID)

	if len(ret) == 0 {
		panic("no return value specified for InNamespace")
	}

	var r0 store.QueryOption
	if returnFunc, ok := ret.Get(0).(func(string) store.QueryOption); ok {
		r0 = returnFunc(tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(store.QueryOption)
		}
	}
	return r0
}

// QueryOptions_InNamespace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InNamespace'
type QueryOptions_InNamespace_Call struct {
	*mock.Call
}

// InNamespace is a helper method to define mock.On call
//   - tenantID string
func (_e *QueryOptions_Expecter) InNamespace(tenantID any) *QueryOptions_InNamespace_Call {
	return &QueryOptions_InNamespace_Call{Call: _e.mock.On("InNamespace", tenantID)}
}

func (_c *QueryOptions_InNamespace_Call) Run(run func(tenantID string)) *QueryOptions_InNamespace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *QueryOptions_InNamespace_Call) Return(queryOption store.QueryOption) *QueryOptions_InNamespace_Call {
	_c.Call.Return(queryOption)
	return _c
}

func (_c *QueryOptions_InNamespace_Call) RunAndReturn(run func(tenantID string) store.QueryOption) *QueryOptions_InNamespace_Call {
	_c.Call.Return(run)
	return _c
}

// Match provides a mock function for the type QueryOptions
func (_mock *QueryOptions) Match(fs *query.Filters) store.QueryOption {
	ret := _mock.Called(fs)

	if len(ret) == 0 {
		panic("no return value specified for Match")
	}

	var r0 store.QueryOption
	if returnFunc, ok := ret.Get(0).(func(*query.Filters) store.QueryOption); ok {
		r0 = returnFunc(fs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(store.QueryOption)
		}
	}
	return r0
}

// QueryOptions_Match_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Match'
type QueryOptions_Match_Call struct {
	*mock.Call
}

// Match is a helper method to define mock.On call
//   - fs *query.Filters
func (_e *QueryOptions_Expecter) Match(fs any) *QueryOptions_Match_Call {
	return &QueryOptions_Match_Call{Call: _e.mock.On("Match", fs)}
}

func (_c *QueryOptions_Match_Call) Run(run func(fs *query.Filters)) *QueryOptions_Match_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *query.Filters
		if args[0] != nil {
			arg0 = args[0].(*query.Filters)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *QueryOptions_Match_Call) Return(queryOption store.QueryOption) *QueryOptions_Match_Call {
	_c.Call.Return(queryOption)
	return _c
}

func (_c *QueryOptions_Match_Call) RunAndReturn(run func(fs *query.Filters) store.QueryOption) *QueryOptions_Match_Call {
	_c.Call.Return(run)
	return _c
}

// Paginate provides a mock function for the type QueryOptions
func (_mock *QueryOptions) Paginate(paginator *query.Paginator) store.QueryOption {
	ret := _mock.Called(paginator)

	if len(ret) == 0 {
		panic("no return value specified for Paginate")
	}

	var r0 store.QueryOption
	if returnFunc, ok := ret.Get(0).(func(*query.Paginator) store.QueryOption); ok {
		r0 = returnFunc(paginator)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(store.QueryOption)
		}
	}
	return r0
}

// QueryOptions_Paginate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Paginate'
type QueryOptions_Paginate_Call struct {
	*mock.Call
}

// Paginate is a helper method to define mock.On call
//   - paginator *query.Paginator
func (_e *QueryOptions_Expecter) Paginate(paginator any) *QueryOptions_Paginate_Call {
	return &QueryOptions_Paginate_Call{Call: _e.mock.On("Paginate", paginator)}
}

func (_c *QueryOptions_Paginate_Call) Run(run func(paginator *query.Paginator)) *QueryOptions_Paginate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *query.Paginator
		if args[0] != nil {
			arg0 = args[0].(*query.Paginator)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *QueryOptions_Paginate_Call) Return(queryOption store.QueryOption) *QueryOptions_Paginate_Call {
	_c.Call.Return(queryOption)
	return _c
}

func (_c *QueryOptions_Paginate_Call) RunAndReturn(run func(paginator *query.Paginator) store.QueryOption) *QueryOptions_Paginate_Call {
	_c.Call.Return(run)
	return _c
}

// Sort provides a mock function for the type QueryOptions
func (_mock *QueryOptions) Sort(sorter *query.Sorter) store.QueryOption {
	ret := _mock.Called(sorter)

	if len(ret) == 0 {
		panic("no return value specified for Sort")
	}

	var r0 store.QueryOption
	if returnFunc, ok := ret.Get(0).(func(*query.Sorter) store.QueryOption); ok {
		r0 = returnFunc(sorter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(store.QueryOption)
		}
	}
	return r0
}

// QueryOptions_Sort_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sort'
type QueryOptions_Sort_Call struct {
	*mock.Call
}

// Sort is a helper method to define mock.On call
//   - sorter *query.Sorter
func (_e *QueryOptions_Expecter) Sort(sorter any) *QueryOptions_Sort_Call {
	return &QueryOptions_Sort_Call{Call: _e.mock.On("Sort", sorter)}
}

func (_c *QueryOptions_Sort_Call) Run(run func(sorter *query.Sorter)) *QueryOptions_Sort_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *query.Sorter
		if args[0] != nil {
			arg0 = args[0].(*query.Sorter)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *QueryOptions_Sort_Call) Return(queryOption store.QueryOption) *QueryOptions_Sort_Call {
	_c.Call.Return(queryOption)
	return _c
}

func (_c *QueryOptions_Sort_Call) RunAndReturn(run func(sorter *query.Sorter) store.QueryOption) *QueryOptions_Sort_Call {
	_c.Call.Return(run)
	return _c
}

// WithDeviceStatus provides a mock function for the type QueryOptions
func (_mock *QueryOptions) WithDeviceStatus(deviceStatus models.DeviceStatus) store.QueryOption {
	ret := _mock.Called(deviceStatus)

	if len(ret) == 0 {
		panic("no return value specified for WithDeviceStatus")
	}

	var r0 store.QueryOption
	if returnFunc, ok := ret.Get(0).(func(models.DeviceStatus) store.QueryOption); ok {
		r0 = returnFunc(deviceStatus)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(store.QueryOption)
		}
	}
	return r0
}

// QueryOptions_WithDeviceStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithDeviceStatus'
type QueryOptions_WithDeviceStatus_Call struct {
	*mock.Call
}

// WithDeviceStatus is a helper method to define mock.On call
//   - deviceStatus models.DeviceStatus
func (_e *QueryOptions_Expecter) WithDeviceStatus(deviceStatus any) *QueryOptions_WithDeviceStatus_Call {
	return &QueryOptions_WithDeviceStatus_Call{Call: _e.mock.On("WithDeviceStatus", deviceStatus)}
}

func (_c *QueryOptions_WithDeviceStatus_Call) Run(run func(deviceStatus models.DeviceStatus)) *QueryOptions_WithDeviceStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 models.DeviceStatus
		if args[0] != nil {
			arg0 = args[0].(models.DeviceStatus)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *QueryOptions_WithDeviceStatus_Call) Return(queryOption store.QueryOption) *QueryOptions_WithDeviceStatus_Call {
	_c.Call.Return(queryOption)
	return _c
}

func (_c *QueryOptions_WithDeviceStatus_Call) RunAndReturn(run func(deviceStatus models.DeviceStatus) store.QueryOption) *QueryOptions_WithDeviceStatus_Call {
	_c.Call.Return(run)
	return _c
}

// WithMember provides a mock function for the type QueryOptions
func (_mock *QueryOptions) WithMember(userID string) store.QueryOption {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for WithMember")
	}

	var r0 store.QueryOption
	if returnFunc, ok := ret.Get(0).(func(string) store.QueryOption); ok {
		r0 = returnFunc(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(store.QueryOption)
		}
	}
	return r0
}

// QueryOptions_WithMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithMember'
type QueryOptions_WithMember_Call struct {
	*mock.Call
}

// WithMember is a helper method to define mock.On call
//   - userID string
func (_e *QueryOptions_Expecter) WithMember(userID any) *QueryOptions_WithMember_Call {
	return &QueryOptions_WithMember_Call{Call: _e.mock.On("WithMember", userID)}
}

func (_c *QueryOptions_WithMember_Call) Run(run func(userID string)) *QueryOptions_WithMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *QueryOptions_WithMember_Call) Return(queryOption store.QueryOption) *QueryOptions_WithMember_Call {
	_c.Call.Return(queryOption)
	return _c
}

func (_c *QueryOptions_WithMember_Call) RunAndReturn(run func(userID string) store.QueryOption) *QueryOptions_WithMember_Call {
	_c.Call.Return(run)
	return _c
}
