// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockHasher creates a new instance of MockHasher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHasher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHasher {
	mock := &MockHasher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHasher is an autogenerated mock type for the Hasher type
type MockHasher struct {
	mock.Mock
}

type MockHasher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHasher) EXPECT() *MockHasher_Expecter {
	return &MockHasher_Expecter{mock: &_m.Mock}
}

// CompareWith provides a mock function for the type MockHasher
func (_mock *MockHasher) CompareWith(plain string, hash string) bool {
	ret := _mock.Called(plain, hash)

	if len(ret) == 0 {
		panic("no return value specified for CompareWith")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = returnFunc(plain, hash)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockHasher_CompareWith_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompareWith'
type MockHasher_CompareWith_Call struct {
	*mock.Call
}

// CompareWith is a helper method to define mock.On call
//   - plain string
//   - hash string
func (_e *MockHasher_Expecter) CompareWith(plain any, hash any) *MockHasher_CompareWith_Call {
	return &MockHasher_CompareWith_Call{Call: _e.mock.On("CompareWith", plain, hash)}
}

func (_c *MockHasher_CompareWith_Call) Run(run func(plain string, hash string)) *MockHasher_CompareWith_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHasher_CompareWith_Call) Return(b bool) *MockHasher_CompareWith_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockHasher_CompareWith_Call) RunAndReturn(run func(plain string, hash string) bool) *MockHasher_CompareWith_Call {
	_c.Call.Return(run)
	return _c
}

// Do provides a mock function for the type MockHasher
func (_mock *MockHasher) Do(plain string) (string, error) {
	ret := _mock.Called(plain)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(plain)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(plain)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(plain)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHasher_Do_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Do'
type MockHasher_Do_Call struct {
	*mock.Call
}

// Do is a helper method to define mock.On call
//   - plain string
func (_e *MockHasher_Expecter) Do(plain any) *MockHasher_Do_Call {
	return &MockHasher_Do_Call{Call: _e.mock.On("Do", plain)}
}

func (_c *MockHasher_Do_Call) Run(run func(plain string)) *MockHasher_Do_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHasher_Do_Call) Return(s string, err error) *MockHasher_Do_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockHasher_Do_Call) RunAndReturn(run func(plain string) (string, error)) *MockHasher_Do_Call {
	_c.Call.Return(run)
	return _c
}
