/* eslint-disable */
// @ts-nocheck

/*

All environment variables should be read by this wrapper, which handles
the difference between development and production environments.
In production mode, the environment variables are stored in the global
`window.env` object, which is automatically generated by the container's
entrypoint in the `/env.js` file.
This is necessary because direct access to system environment variables
is not possible. On the other hand, in development mode, environment
variables can be accessed directly through `process.env` object.

*/

const env = (window.env || process.env);
export const envVariables = {
  isEnterprise: env.VUE_APP_SHELLHUB_ENTERPRISE === "true",
  hasConnector: env.VUE_APP_SHELLHUB_CONNECTOR === "true",
  hasWebEndpoints: env.VUE_APP_SHELLHUB_WEB_ENDPOINTS === "true",
  tunnelsDomain: env.VUE_APP_SHELLHUB_WEB_ENDPOINTS_DOMAIN as string,
  isCloud: env.VUE_APP_SHELLHUB_CLOUD === "true",
  isCommunity: env.VUE_APP_SHELLHUB_CLOUD === "false" && env.VUE_APP_SHELLHUB_ENTERPRISE === "false",
  premiumPaywall: env.VUE_APP_SHELLHUB_PAYWALL === "true",
  stripePublishableKey: env.VUE_APP_SHELLHUB_STRIPE_PUBLISHABLE_KEY as string,
  chatWootWebsiteToken: env.VUE_APP_SHELLHUB_CHATWOOT_WEBSITE_TOKEN as string,
  chatWootBaseURL: env.VUE_APP_SHELLHUB_CHATWOOT_BASEURL as string,
  version: env.VUE_APP_SHELLHUB_VERSION as string,
  isAnnouncementsEnabled: env.VUE_APP_SHELLHUB_ANNOUNCEMENTS === "true",
  tinyMceKey: env.VUE_APP_SHELLHUB_TINYMCE_API_KEY as string,
  stripeKey: env.VUE_APP_SHELLHUB_STRIPE_PUBLISHABLE_KEY as string,
  sentryDsn: env.VUE_APP_SHELLHUB_SENTRY_DSN_VERSION as string,
  googleAnalyticsID: env.VUE_APP_SHELLHUB_GOOGLE_ANALYTICS_ID as string,
};
