/*
ShellHub Community

ShellHub Community documentation.  It documents all routes provided by ShellHub Community.   NOTICE: THE API IS NOT STABLE YET; ERROR AND INCONSISTENCIES MAY OCCUR. 

API version: 0.1.0
Contact: contato@ossystems.com.br
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CreateDeviceTagRequest struct for CreateDeviceTagRequest
type CreateDeviceTagRequest struct {
	// Tag's name.
	Tag string `json:"tag"`
}

// NewCreateDeviceTagRequest instantiates a new CreateDeviceTagRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateDeviceTagRequest(tag string) *CreateDeviceTagRequest {
	this := CreateDeviceTagRequest{}
	this.Tag = tag
	return &this
}

// NewCreateDeviceTagRequestWithDefaults instantiates a new CreateDeviceTagRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateDeviceTagRequestWithDefaults() *CreateDeviceTagRequest {
	this := CreateDeviceTagRequest{}
	return &this
}

// GetTag returns the Tag field value
func (o *CreateDeviceTagRequest) GetTag() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Tag
}

// GetTagOk returns a tuple with the Tag field value
// and a boolean to check if the value has been set.
func (o *CreateDeviceTagRequest) GetTagOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tag, true
}

// SetTag sets field value
func (o *CreateDeviceTagRequest) SetTag(v string) {
	o.Tag = v
}

func (o CreateDeviceTagRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["tag"] = o.Tag
	}
	return json.Marshal(toSerialize)
}

type NullableCreateDeviceTagRequest struct {
	value *CreateDeviceTagRequest
	isSet bool
}

func (v NullableCreateDeviceTagRequest) Get() *CreateDeviceTagRequest {
	return v.value
}

func (v *NullableCreateDeviceTagRequest) Set(val *CreateDeviceTagRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateDeviceTagRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateDeviceTagRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateDeviceTagRequest(val *CreateDeviceTagRequest) *NullableCreateDeviceTagRequest {
	return &NullableCreateDeviceTagRequest{value: val, isSet: true}
}

func (v NullableCreateDeviceTagRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateDeviceTagRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


