/*
ShellHub Community

ShellHub Community documentation.  It documents all routes provided by ShellHub Community.   NOTICE: THE API IS NOT STABLE YET; ERROR AND INCONSISTENCIES MAY OCCUR. 

API version: 0.1.0
Contact: contato@ossystems.com.br
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// UpdateTagsDeviceRequest struct for UpdateTagsDeviceRequest
type UpdateTagsDeviceRequest struct {
	// Device's Tags list
	Tags []string `json:"tags"`
}

// NewUpdateTagsDeviceRequest instantiates a new UpdateTagsDeviceRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateTagsDeviceRequest(tags []string) *UpdateTagsDeviceRequest {
	this := UpdateTagsDeviceRequest{}
	this.Tags = tags
	return &this
}

// NewUpdateTagsDeviceRequestWithDefaults instantiates a new UpdateTagsDeviceRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateTagsDeviceRequestWithDefaults() *UpdateTagsDeviceRequest {
	this := UpdateTagsDeviceRequest{}
	return &this
}

// GetTags returns the Tags field value
func (o *UpdateTagsDeviceRequest) GetTags() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value
// and a boolean to check if the value has been set.
func (o *UpdateTagsDeviceRequest) GetTagsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tags, true
}

// SetTags sets field value
func (o *UpdateTagsDeviceRequest) SetTags(v []string) {
	o.Tags = v
}

func (o UpdateTagsDeviceRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["tags"] = o.Tags
	}
	return json.Marshal(toSerialize)
}

type NullableUpdateTagsDeviceRequest struct {
	value *UpdateTagsDeviceRequest
	isSet bool
}

func (v NullableUpdateTagsDeviceRequest) Get() *UpdateTagsDeviceRequest {
	return v.value
}

func (v *NullableUpdateTagsDeviceRequest) Set(val *UpdateTagsDeviceRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateTagsDeviceRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateTagsDeviceRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateTagsDeviceRequest(val *UpdateTagsDeviceRequest) *NullableUpdateTagsDeviceRequest {
	return &NullableUpdateTagsDeviceRequest{value: val, isSet: true}
}

func (v NullableUpdateTagsDeviceRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateTagsDeviceRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


