/*
ShellHub Community

ShellHub Community documentation.  It documents all routes provided by ShellHub Community.   NOTICE: THE API IS NOT STABLE YET; ERROR AND INCONSISTENCIES MAY OCCUR. 

API version: 0.1.0
Contact: contato@ossystems.com.br
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// AddTagPublicKeyRequest struct for AddTagPublicKeyRequest
type AddTagPublicKeyRequest struct {
	// Tag's name.
	Tag string `json:"tag"`
}

// NewAddTagPublicKeyRequest instantiates a new AddTagPublicKeyRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddTagPublicKeyRequest(tag string) *AddTagPublicKeyRequest {
	this := AddTagPublicKeyRequest{}
	this.Tag = tag
	return &this
}

// NewAddTagPublicKeyRequestWithDefaults instantiates a new AddTagPublicKeyRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddTagPublicKeyRequestWithDefaults() *AddTagPublicKeyRequest {
	this := AddTagPublicKeyRequest{}
	return &this
}

// GetTag returns the Tag field value
func (o *AddTagPublicKeyRequest) GetTag() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Tag
}

// GetTagOk returns a tuple with the Tag field value
// and a boolean to check if the value has been set.
func (o *AddTagPublicKeyRequest) GetTagOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tag, true
}

// SetTag sets field value
func (o *AddTagPublicKeyRequest) SetTag(v string) {
	o.Tag = v
}

func (o AddTagPublicKeyRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["tag"] = o.Tag
	}
	return json.Marshal(toSerialize)
}

type NullableAddTagPublicKeyRequest struct {
	value *AddTagPublicKeyRequest
	isSet bool
}

func (v NullableAddTagPublicKeyRequest) Get() *AddTagPublicKeyRequest {
	return v.value
}

func (v *NullableAddTagPublicKeyRequest) Set(val *AddTagPublicKeyRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAddTagPublicKeyRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAddTagPublicKeyRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddTagPublicKeyRequest(val *AddTagPublicKeyRequest) *NullableAddTagPublicKeyRequest {
	return &NullableAddTagPublicKeyRequest{value: val, isSet: true}
}

func (v NullableAddTagPublicKeyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddTagPublicKeyRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


