// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"net"

	"github.com/shellhub-io/shellhub/pkg/geoip"
	mock "github.com/stretchr/testify/mock"
)

// NewMockLocator creates a new instance of MockLocator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLocator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLocator {
	mock := &MockLocator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLocator is an autogenerated mock type for the Locator type
type MockLocator struct {
	mock.Mock
}

type MockLocator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLocator) EXPECT() *MockLocator_Expecter {
	return &MockLocator_Expecter{mock: &_m.Mock}
}

// GetCountry provides a mock function for the type MockLocator
func (_mock *MockLocator) GetCountry(ip net.IP) (string, error) {
	ret := _mock.Called(ip)

	if len(ret) == 0 {
		panic("no return value specified for GetCountry")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(net.IP) (string, error)); ok {
		return returnFunc(ip)
	}
	if returnFunc, ok := ret.Get(0).(func(net.IP) string); ok {
		r0 = returnFunc(ip)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(net.IP) error); ok {
		r1 = returnFunc(ip)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLocator_GetCountry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCountry'
type MockLocator_GetCountry_Call struct {
	*mock.Call
}

// GetCountry is a helper method to define mock.On call
//   - ip net.IP
func (_e *MockLocator_Expecter) GetCountry(ip any) *MockLocator_GetCountry_Call {
	return &MockLocator_GetCountry_Call{Call: _e.mock.On("GetCountry", ip)}
}

func (_c *MockLocator_GetCountry_Call) Run(run func(ip net.IP)) *MockLocator_GetCountry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 net.IP
		if args[0] != nil {
			arg0 = args[0].(net.IP)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLocator_GetCountry_Call) Return(s string, err error) *MockLocator_GetCountry_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockLocator_GetCountry_Call) RunAndReturn(run func(ip net.IP) (string, error)) *MockLocator_GetCountry_Call {
	_c.Call.Return(run)
	return _c
}

// GetPosition provides a mock function for the type MockLocator
func (_mock *MockLocator) GetPosition(ip net.IP) (geoip.Position, error) {
	ret := _mock.Called(ip)

	if len(ret) == 0 {
		panic("no return value specified for GetPosition")
	}

	var r0 geoip.Position
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(net.IP) (geoip.Position, error)); ok {
		return returnFunc(ip)
	}
	if returnFunc, ok := ret.Get(0).(func(net.IP) geoip.Position); ok {
		r0 = returnFunc(ip)
	} else {
		r0 = ret.Get(0).(geoip.Position)
	}
	if returnFunc, ok := ret.Get(1).(func(net.IP) error); ok {
		r1 = returnFunc(ip)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLocator_GetPosition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPosition'
type MockLocator_GetPosition_Call struct {
	*mock.Call
}

// GetPosition is a helper method to define mock.On call
//   - ip net.IP
func (_e *MockLocator_Expecter) GetPosition(ip any) *MockLocator_GetPosition_Call {
	return &MockLocator_GetPosition_Call{Call: _e.mock.On("GetPosition", ip)}
}

func (_c *MockLocator_GetPosition_Call) Run(run func(ip net.IP)) *MockLocator_GetPosition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 net.IP
		if args[0] != nil {
			arg0 = args[0].(net.IP)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLocator_GetPosition_Call) Return(position geoip.Position, err error) *MockLocator_GetPosition_Call {
	_c.Call.Return(position, err)
	return _c
}

func (_c *MockLocator_GetPosition_Call) RunAndReturn(run func(ip net.IP) (geoip.Position, error)) *MockLocator_GetPosition_Call {
	_c.Call.Return(run)
	return _c
}
