# base stage
FROM golang:1.23.7-alpine3.21 AS base

RUN apk add --no-cache git ca-certificates

WORKDIR $GOPATH/src/github.com/shellhub-io/shellhub
COPY ./go.mod ./go.sum ./

WORKDIR $GOPATH/src/github.com/shellhub-io/shellhub/server
COPY ./server/go.mod ./server/go.sum ./

WORKDIR $GOPATH/src/github.com/shellhub-io/shellhub/cli
COPY ./cli/go.mod ./cli/go.sum ./

RUN go mod download

COPY ./server $GOPATH/src/github.com/shellhub-io/shellhub/server
COPY ./pkg $GOPATH/src/github.com/shellhub-io/shellhub/pkg
COPY ./cli .

WORKDIR $GOPATH/src/github.com/shellhub-io/shellhub

RUN go mod download

WORKDIR $GOPATH/src/github.com/shellhub-io/shellhub/cli

RUN go build
