// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	client "github.com/shellhub-io/shellhub/pkg/api/client"

	mock "github.com/stretchr/testify/mock"

	models "github.com/shellhub-io/shellhub/pkg/models"

	net "net"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// AuthDevice provides a mock function with given fields: req
func (_m *Client) AuthDevice(req *models.DeviceAuthRequest) (*models.DeviceAuthResponse, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for AuthDevice")
	}

	var r0 *models.DeviceAuthResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*models.DeviceAuthRequest) (*models.DeviceAuthResponse, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(*models.DeviceAuthRequest) *models.DeviceAuthResponse); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.DeviceAuthResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*models.DeviceAuthRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthPublicKey provides a mock function with given fields: req, token
func (_m *Client) AuthPublicKey(req *models.PublicKeyAuthRequest, token string) (*models.PublicKeyAuthResponse, error) {
	ret := _m.Called(req, token)

	if len(ret) == 0 {
		panic("no return value specified for AuthPublicKey")
	}

	var r0 *models.PublicKeyAuthResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*models.PublicKeyAuthRequest, string) (*models.PublicKeyAuthResponse, error)); ok {
		return rf(req, token)
	}
	if rf, ok := ret.Get(0).(func(*models.PublicKeyAuthRequest, string) *models.PublicKeyAuthResponse); ok {
		r0 = rf(req, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PublicKeyAuthResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*models.PublicKeyAuthRequest, string) error); ok {
		r1 = rf(req, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateDeviceLoginCode provides a mock function with given fields: token
func (_m *Client) CreateDeviceLoginCode(token string) (*models.DeviceLoginCode, error) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for CreateDeviceLoginCode")
	}

	var r0 *models.DeviceLoginCode
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.DeviceLoginCode, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) *models.DeviceLoginCode); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.DeviceLoginCode)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateDevicePairing provides a mock function with given fields: req
func (_m *Client) CreateDevicePairing(req *models.DevicePairingRequest) (*models.DevicePairing, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for CreateDevicePairing")
	}

	var r0 *models.DevicePairing
	var r1 error
	if rf, ok := ret.Get(0).(func(*models.DevicePairingRequest) (*models.DevicePairing, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(*models.DevicePairingRequest) *models.DevicePairing); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.DevicePairing)
		}
	}

	if rf, ok := ret.Get(1).(func(*models.DevicePairingRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDevicePairingStatus provides a mock function with given fields: code
func (_m *Client) GetDevicePairingStatus(code string) (*models.DevicePairingStatus, error) {
	ret := _m.Called(code)

	if len(ret) == 0 {
		panic("no return value specified for GetDevicePairingStatus")
	}

	var r0 *models.DevicePairingStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.DevicePairingStatus, error)); ok {
		return rf(code)
	}
	if rf, ok := ret.Get(0).(func(string) *models.DevicePairingStatus); ok {
		r0 = rf(code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.DevicePairingStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDeviceAuthStatus provides a mock function with given fields: token
func (_m *Client) GetDeviceAuthStatus(token string) (*models.DeviceAuthStatus, error) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for GetDeviceAuthStatus")
	}

	var r0 *models.DeviceAuthStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.DeviceAuthStatus, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) *models.DeviceAuthStatus); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.DeviceAuthStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Endpoints provides a mock function with no fields
func (_m *Client) Endpoints() (*models.Endpoints, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Endpoints")
	}

	var r0 *models.Endpoints
	var r1 error
	if rf, ok := ret.Get(0).(func() (*models.Endpoints, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *models.Endpoints); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Endpoints)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDevice provides a mock function with given fields: uid
func (_m *Client) GetDevice(uid string) (*models.Device, error) {
	ret := _m.Called(uid)

	if len(ret) == 0 {
		panic("no return value specified for GetDevice")
	}

	var r0 *models.Device
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.Device, error)); ok {
		return rf(uid)
	}
	if rf, ok := ret.Get(0).(func(string) *models.Device); ok {
		r0 = rf(uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Device)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(uid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetInfo provides a mock function with given fields: agentVersion
func (_m *Client) GetInfo(agentVersion string) (*models.Info, error) {
	ret := _m.Called(agentVersion)

	if len(ret) == 0 {
		panic("no return value specified for GetInfo")
	}

	var r0 *models.Info
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.Info, error)); ok {
		return rf(agentVersion)
	}
	if rf, ok := ret.Get(0).(func(string) *models.Info); ok {
		r0 = rf(agentVersion)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Info)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(agentVersion)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListDevices provides a mock function with no fields
func (_m *Client) ListDevices() ([]models.Device, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListDevices")
	}

	var r0 []models.Device
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.Device, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.Device); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Device)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewReverseListenerV1 provides a mock function with given fields: ctx, token, path
func (_m *Client) NewReverseListenerV1(ctx context.Context, token string, path string) (net.Listener, error) {
	ret := _m.Called(ctx, token, path)

	if len(ret) == 0 {
		panic("no return value specified for NewReverseListenerV1")
	}

	var r0 net.Listener
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (net.Listener, error)); ok {
		return rf(ctx, token, path)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) net.Listener); ok {
		r0 = rf(ctx, token, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(net.Listener)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, token, path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewReverseListenerV2 provides a mock function with given fields: ctx, token, path, cfg
func (_m *Client) NewReverseListenerV2(ctx context.Context, token string, path string, cfg *client.ReverseListenerV2Config) (net.Listener, error) {
	ret := _m.Called(ctx, token, path, cfg)

	if len(ret) == 0 {
		panic("no return value specified for NewReverseListenerV2")
	}

	var r0 net.Listener
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *client.ReverseListenerV2Config) (net.Listener, error)); ok {
		return rf(ctx, token, path, cfg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *client.ReverseListenerV2Config) net.Listener); ok {
		r0 = rf(ctx, token, path, cfg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(net.Listener)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *client.ReverseListenerV2Config) error); ok {
		r1 = rf(ctx, token, path, cfg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
