name: Bug report
description: Report a bug or issue
labels: ["kind/bug", "triage"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the issue
      placeholder: |
        What happened? What did you expect?

        Include steps to reproduce, version, logs, or anything else that might help.
    validations:
      required: true
