import { useState, useEffect, useCallback, FormEvent } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import {
  CheckIcon,
  DocumentDuplicateIcon,
  ExclamationCircleIcon,
  EyeSlashIcon,
  EyeIcon,
} from "@heroicons/react/24/outline";
import { setup } from "../api/system";
import { getConfig } from "../env";
import { validate, type FormErrors } from "./setup/validate";

const STEP_SIGN = 1;
const STEP_ONBOARDING = 2;
const STEP_ACCOUNT = 3;

export default function Setup() {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const config = getConfig();

  const signFromQuery = searchParams.get("sign") || "";

  const isCommunity = !config.cloud && !config.enterprise;
  const showOnboarding = isCommunity && !!config.onboardingUrl;

  const nextAfterSign = showOnboarding ? STEP_ONBOARDING : STEP_ACCOUNT;
  const initialStep = signFromQuery ? nextAfterSign : STEP_SIGN;

  const [step, setStep] = useState(initialStep);
  const [sign, setSign] = useState(signFromQuery);
  const [name, setName] = useState("");
  const [username, setUsername] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [showPassword, setShowPassword] = useState(false);
  const [showConfirm, setShowConfirm] = useState(false);
  const [touched, setTouched] = useState<Record<string, boolean>>({});
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [success, setSuccess] = useState(false);
  const [copied, setCopied] = useState(false);
  const [surveyCompleted, setSurveyCompleted] = useState(false);

  const errors = validate({ name, username, email, password, confirmPassword });

  const onboardingUrl = (() => {
    if (!config.onboardingUrl) return "";
    const params = new URLSearchParams({
      consent_to_contact: "accepted",
      source: "self-hosted",
      embed: "true",
      instance_domain: window.location.hostname,
    });
    if (import.meta.env.DEV) params.append("preview", "true");
    return `${config.onboardingUrl}?${params.toString()}`;
  })();

  const handleMessage = useCallback(
    (event: MessageEvent) => {
      if (!config.onboardingUrl) return;
      try {
        const origin = new URL(config.onboardingUrl).origin;
        if (event.origin !== origin) return;
      } catch {
        return;
      }
      if (event.data === "formbricksSurveyCompleted") {
        setSurveyCompleted(true);
      }
    },
    [config.onboardingUrl],
  );

  useEffect(() => {
    if (!showOnboarding) return;
    window.addEventListener("message", handleMessage);
    return () => window.removeEventListener("message", handleMessage);
  }, [showOnboarding, handleMessage]);

  useEffect(() => {
    if (success) {
      const timer = setTimeout(
        () => void navigate("/login", { replace: true }),
        3000,
      );
      return () => clearTimeout(timer);
    }
  }, [success, navigate]);

  const handleBlur = (field: string) => {
    setTouched((prev) => ({ ...prev, [field]: true }));
  };

  const showError = (field: keyof FormErrors) =>
    touched[field] ? errors[field] : undefined;

  const handleCopy = () => {
    void navigator.clipboard.writeText("./bin/setup");
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleNextStep = (e: FormEvent) => {
    e.preventDefault();
    if (sign.trim()) {
      setStep(nextAfterSign);
    }
  };

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();

    setTouched({
      name: true,
      username: true,
      email: true,
      password: true,
      confirmPassword: true,
    });

    if (Object.keys(errors).length > 0) return;

    setLoading(true);
    setError("");

    try {
      await setup(sign, { name, username, email, password });
      setSuccess(true);
    } catch (err: unknown) {
      if (
        err
        && typeof err === "object"
        && "response" in err
        && (err as { response?: { status?: number } }).response?.status === 409
      ) {
        setError("Setup has already been completed.");
      } else {
        setError(
          "An error occurred. Please check if the signature matches the one generated by the command and try again.",
        );
      }
    } finally {
      setLoading(false);
    }
  };

  const totalSteps = showOnboarding ? 3 : 2;
  const displayStep = (() => {
    if (step === STEP_SIGN) return 1;
    if (step === STEP_ONBOARDING) return 2;
    return showOnboarding ? 3 : 2;
  })();

  if (success) {
    return (
      <div className="w-full max-w-sm mx-auto animate-fade-in">
        <div className="bg-surface border border-border rounded-lg overflow-hidden">
          <div className="px-8 pt-8 pb-6 border-b border-border bg-card/50">
            <div className="flex justify-center mb-5">
              <img src="/logo.svg" alt="ShellHub" className="h-7" />
            </div>
            <p className="text-center text-2xs font-mono text-text-muted tracking-wider uppercase">
              Initial Setup
            </p>
          </div>

          <div className="p-8 text-center">
            <div className="inline-flex items-center justify-center w-12 h-12 rounded-full bg-accent-green/10 mb-4">
              <CheckIcon
                className="w-6 h-6 text-accent-green"
                strokeWidth={2}
              />
            </div>
            <h3 className="text-sm font-semibold text-text-primary mb-2">
              Account created successfully
            </h3>
            <p className="text-xs text-text-secondary leading-relaxed">
              Redirecting to login in a few seconds...
            </p>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div
      className={`w-full mx-auto animate-fade-in ${step === STEP_ONBOARDING ? "max-w-lg" : "max-w-sm"}`}
    >
      <div className="bg-surface border border-border rounded-lg overflow-hidden">
        <div className="px-8 pt-8 pb-6 border-b border-border bg-card/50">
          <div className="flex justify-center mb-5">
            <img src="/logo.svg" alt="ShellHub" className="h-7" />
          </div>
          <h1 className="text-center text-sm font-semibold text-text-primary mb-1">
            Welcome to ShellHub
          </h1>
          <p className="text-center text-2xs font-mono text-text-muted tracking-wider uppercase">
            Initial Setup
          </p>

          <div className="flex items-center justify-center gap-2 mt-4">
            {Array.from({ length: totalSteps }, (_, i) => (
              <StepIndicator key={i} index={i} current={displayStep} />
            ))}
          </div>
        </div>

        <div className="p-8">
          {error && (
            <div className="flex items-start gap-2 bg-accent-red/8 border border-accent-red/20 text-accent-red px-3.5 py-2.5 rounded-md text-xs font-mono animate-slide-down mb-5">
              <ExclamationCircleIcon
                className="w-3.5 h-3.5 shrink-0 mt-0.5"
                strokeWidth={2}
              />
              {error}
            </div>
          )}

          {step === STEP_SIGN && (
            <form onSubmit={handleNextStep} className="space-y-5">
              <p className="text-xs text-text-secondary leading-relaxed">
                Run the following command in your terminal to generate a setup
                signature, then paste it below to proceed.
              </p>

              <div>
                <label className="block text-2xs font-mono font-semibold uppercase tracking-label text-text-muted mb-2">
                  Setup Command
                </label>
                <div className="flex items-center bg-card border border-border rounded-md overflow-hidden">
                  <span className="pl-3.5 text-text-muted font-mono text-xs select-none">
                    $
                  </span>
                  <code className="flex-1 text-xs font-mono text-primary px-2 py-2.5 select-all">
                    ./bin/setup
                  </code>
                  <button
                    type="button"
                    onClick={handleCopy}
                    className="px-3 py-2.5 text-text-muted hover:text-text-secondary border-l border-border hover:bg-border/30 transition-colors"
                    title="Copy command"
                  >
                    {copied
                      ? (
                        <CheckIcon
                          className="w-4 h-4 text-accent-green"
                          strokeWidth={2}
                        />
                      )
                      : (
                        <DocumentDuplicateIcon className="w-4 h-4" />
                      )}
                  </button>
                </div>
              </div>

              <div>
                <label
                  htmlFor="sign"
                  className="block text-2xs font-mono font-semibold uppercase tracking-label text-text-muted mb-2"
                >
                  Signature
                </label>
                <input
                  id="sign"
                  type="text"
                  value={sign}
                  onChange={(e) => setSign(e.target.value)}
                  required
                  autoFocus
                  className="w-full px-3.5 py-2.5 bg-card border border-border rounded-md text-sm text-text-primary font-mono placeholder:text-text-secondary focus:outline-none focus:border-primary/50 focus:ring-1 focus:ring-primary/20 transition-all duration-200"
                  placeholder="Paste signature here"
                />
              </div>

              <button
                type="submit"
                className="w-full bg-primary hover:bg-primary-600 text-white py-2.5 px-4 rounded-md text-sm font-semibold transition-all duration-200 mt-1"
              >
                Next
              </button>
            </form>
          )}

          {step === STEP_ONBOARDING && (
            <div className="space-y-5">
              <p className="text-xs text-text-secondary leading-relaxed text-center">
                Help us improve ShellHub by sharing your feedback
              </p>

              <div className="relative h-[60dvh] overflow-auto rounded-md border border-border">
                <iframe
                  src={onboardingUrl}
                  title="Onboarding survey"
                  className="absolute inset-0 w-full h-full border-0"
                />
              </div>

              <div className="flex gap-3 pt-1">
                <button
                  type="button"
                  onClick={() => setStep(STEP_SIGN)}
                  className="flex-1 bg-card hover:bg-border/50 border border-border text-text-secondary py-2.5 px-4 rounded-md text-sm font-semibold transition-all duration-200"
                >
                  Back
                </button>
                <button
                  type="button"
                  disabled={!surveyCompleted}
                  onClick={() => setStep(STEP_ACCOUNT)}
                  className="flex-[2] bg-primary hover:bg-primary-600 text-white py-2.5 px-4 rounded-md text-sm font-semibold disabled:opacity-dim disabled:cursor-not-allowed transition-all duration-200"
                >
                  Continue
                </button>
              </div>
            </div>
          )}

          {step === STEP_ACCOUNT && (
            <form onSubmit={(e) => void handleSubmit(e)} className="space-y-4">
              <p className="text-xs text-text-secondary leading-relaxed mb-1">
                Set up your admin account with your personal information.
              </p>

              <InputField
                id="name"
                label="Name"
                value={name}
                onChange={setName}
                onBlur={() => handleBlur("name")}
                error={showError("name")}
                placeholder="Your name"
                autoFocus
              />

              <InputField
                id="username"
                label="Username"
                value={username}
                onChange={setUsername}
                onBlur={() => handleBlur("username")}
                error={showError("username")}
                placeholder="username"
              />

              <InputField
                id="email"
                label="Email"
                type="email"
                value={email}
                onChange={setEmail}
                onBlur={() => handleBlur("email")}
                error={showError("email")}
                placeholder="you@example.com"
              />

              <PasswordField
                id="password"
                label="Password"
                value={password}
                onChange={setPassword}
                onBlur={() => handleBlur("password")}
                error={showError("password")}
                placeholder="Min. 5 characters"
                visible={showPassword}
                onToggle={() => setShowPassword((v) => !v)}
              />

              <PasswordField
                id="confirmPassword"
                label="Confirm Password"
                value={confirmPassword}
                onChange={setConfirmPassword}
                onBlur={() => handleBlur("confirmPassword")}
                error={showError("confirmPassword")}
                placeholder="Re-enter password"
                visible={showConfirm}
                onToggle={() => setShowConfirm((v) => !v)}
              />

              <div className="flex gap-3 pt-1">
                <button
                  type="button"
                  onClick={() =>
                    setStep(showOnboarding ? STEP_ONBOARDING : STEP_SIGN)}
                  className="flex-1 bg-card hover:bg-border/50 border border-border text-text-secondary py-2.5 px-4 rounded-md text-sm font-semibold transition-all duration-200"
                >
                  Back
                </button>
                <button
                  type="submit"
                  disabled={loading}
                  className="flex-[2] bg-primary hover:bg-primary-600 text-white py-2.5 px-4 rounded-md text-sm font-semibold disabled:opacity-dim disabled:cursor-not-allowed transition-all duration-200"
                >
                  {loading
                    ? (
                      <span className="flex items-center justify-center gap-2">
                        <span className="w-3.5 h-3.5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                        <span className="font-mono text-xs">Creating...</span>
                      </span>
                    )
                    : (
                      "Create Account"
                    )}
                </button>
              </div>
            </form>
          )}
        </div>
      </div>

      <p className="text-center text-2xs font-mono text-text-muted/40 mt-6">
        ShellHub &mdash; Secure Remote Access
      </p>
    </div>
  );
}

function StepIndicator({ index, current }: { index: number; current: number }) {
  const stepNum = index + 1;
  return (
    <>
      {index > 0 && <div className="w-6 h-px bg-border" />}
      <StepDot active={current === stepNum} label={String(stepNum)} />
    </>
  );
}

function StepDot({ active, label }: { active: boolean; label: string }) {
  return (
    <div
      className={`w-5 h-5 rounded-full flex items-center justify-center text-3xs font-mono font-bold transition-colors ${
        active ? "bg-primary text-white" : "bg-border text-text-muted"
      }`}
    >
      {label}
    </div>
  );
}

function InputField({
  id,
  label,
  type = "text",
  value,
  onChange,
  onBlur,
  error,
  placeholder,
  autoFocus,
}: {
  id: string;
  label: string;
  type?: string;
  value: string;
  onChange: (v: string) => void;
  onBlur: () => void;
  error?: string;
  placeholder: string;
  autoFocus?: boolean;
}) {
  return (
    <div>
      <label
        htmlFor={id}
        className="block text-2xs font-mono font-semibold uppercase tracking-label text-text-muted mb-2"
      >
        {label}
      </label>
      <input
        id={id}
        type={type}
        value={value}
        onChange={(e) => onChange(e.target.value)}
        onBlur={onBlur}
        autoFocus={autoFocus}
        className={`w-full px-3.5 py-2.5 bg-card border rounded-md text-sm text-text-primary font-mono placeholder:text-text-secondary focus:outline-none focus:border-primary/50 focus:ring-1 focus:ring-primary/20 transition-all duration-200 ${
          error ? "border-accent-red/50" : "border-border"
        }`}
        placeholder={placeholder}
      />
      {error && (
        <p className="text-2xs font-mono text-accent-red mt-1.5">{error}</p>
      )}
    </div>
  );
}

function PasswordField({
  id,
  label,
  value,
  onChange,
  onBlur,
  error,
  placeholder,
  visible,
  onToggle,
}: {
  id: string;
  label: string;
  value: string;
  onChange: (v: string) => void;
  onBlur: () => void;
  error?: string;
  placeholder: string;
  visible: boolean;
  onToggle: () => void;
}) {
  return (
    <div>
      <label
        htmlFor={id}
        className="block text-2xs font-mono font-semibold uppercase tracking-label text-text-muted mb-2"
      >
        {label}
      </label>
      <div className="relative">
        <input
          id={id}
          type={visible ? "text" : "password"}
          value={value}
          onChange={(e) => onChange(e.target.value)}
          onBlur={onBlur}
          className={`w-full px-3.5 py-2.5 pr-10 bg-card border rounded-md text-sm text-text-primary font-mono placeholder:text-text-secondary focus:outline-none focus:border-primary/50 focus:ring-1 focus:ring-primary/20 transition-all duration-200 ${
            error ? "border-accent-red/50" : "border-border"
          }`}
          placeholder={placeholder}
        />
        <button
          type="button"
          onClick={onToggle}
          className="absolute right-2.5 top-1/2 -translate-y-1/2 text-text-muted hover:text-text-secondary transition-colors"
          tabIndex={-1}
        >
          {visible
            ? (
              <EyeSlashIcon className="w-4 h-4" />
            )
            : (
              <EyeIcon className="w-4 h-4" />
            )}
        </button>
      </div>
      {error && (
        <p className="text-2xs font-mono text-accent-red mt-1.5">{error}</p>
      )}
    </div>
  );
}
