log-level: "info"
dir: "{{.InterfaceDir}}/mocks"
pkgname: "mocks"
structname: "Mock{{.InterfaceName}}"
filename: "mock_{{.InterfaceName | snakecase}}.go"
template: testify

packages:
  github.com/shellhub-io/shellhub/agent/pkg/osauth:
    interfaces:
      Backend:

  github.com/shellhub-io/shellhub/agent/server/modes:
    interfaces:
      Authenticator:
