FROM golang:1.23.0-alpine3.19

ARG GOPROXY

RUN apk add --update git ca-certificates util-linux build-base bash setpriv perl xz linux-headers

RUN apk add openssh

# We are using libxcrypt to support yescrypt password hashing method
# Since libxcrypt package is not available in Alpine, so we need to build libxcrypt from source code
RUN wget -q https://github.com/besser82/libxcrypt/releases/download/v4.4.36/libxcrypt-4.4.36.tar.xz && \
    tar xvf libxcrypt-4.4.36.tar.xz && cd libxcrypt-4.4.36 && \
    ./configure --prefix /usr && make -j$(nproc) && make install && \
    cd .. && rm -rf libxcrypt-4.4.36*

RUN ln -sf /bin/bash /bin/sh

WORKDIR $GOPATH/src/github.com/shellhub-io/shellhub

COPY ./go.mod ./

WORKDIR $GOPATH/src/github.com/shellhub-io/shellhub/agent

COPY ./agent/go.mod ./agent/go.sum ./

RUN go mod download

ARG SHELLHUB_VERSION=latest
ARG GOPROXY

COPY ./pkg $GOPATH/src/github.com/shellhub-io/shellhub/pkg
COPY ./agent .

WORKDIR $GOPATH/src/github.com/shellhub-io/shellhub

RUN go mod download

WORKDIR $GOPATH/src/github.com/shellhub-io/shellhub/agent

RUN go build -ldflags "-X main.AgentVersion=${SHELLHUB_VERSION}"

ARG USERNAME 
ARG PASSWORD

RUN echo "${USERNAME}:${PASSWORD}" | chpasswd

ENTRYPOINT ./agent
