# docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

FROM arm64v8/golang:alpine

ARG SHELLHUB_VERSION=latest

RUN apk add --update git ca-certificates util-linux build-base bash && \
    go get -u github.com/Masterminds/glide

WORKDIR $GOPATH/src/github.com/shellhub-io/shellhub

COPY ./agent/glide.yaml ./agent/glide.lock ./

RUN glide install

WORKDIR $GOPATH/src/github.com/shellhub-io/shellhub/agent

COPY ./pkg $GOPATH/src/github.com/shellhub-io/shellhub/pkg
COPY ./agent .

WORKDIR $GOPATH/src/github.com/shellhub-io/shellhub

RUN glide -q install --skip-test

WORKDIR $GOPATH/src/github.com/shellhub-io/shellhub/agent

RUN GOOS=linux GOARCH=arm64 go build -tags docker -ldflags "-X main.AgentVersion=${SHELLHUB_VERSION}"

FROM scratch

COPY --from=0 /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=0 /usr/bin/nsenter /usr/bin/
COPY --from=0 /lib/ld-musl-aarch64.so.1 /lib/
COPY --from=0 /go/src/github.com/shellhub-io/shellhub/agent/agent /bin/agent

ENTRYPOINT ["/bin/agent"]
