FROM debian:stretch as builder

ENV DEBIAN_FRONTEND noninteractive

RUN dpkg --add-architecture armhf && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential ca-certificates git curl \
    gcc-arm-linux-gnueabihf libpam-dev:armhf libc6-armhf-cross

ENV GO_VERSION 1.12.6
ENV ARCH amd64

RUN curl https://dl.google.com/go/go$GO_VERSION.linux-$ARCH.tar.gz | tar xz -C /usr/local && mkdir -p /go/bin /go/src

ENV GOPATH=/go \
    PATH=/go/bin/:/usr/local/go/bin/:$PATH

RUN curl https://glide.sh/get | sh

ADD ./glide.yaml .
ADD ./glide.lock .

RUN glide install

WORKDIR $GOPATH/src/github.com/gustavosbarreto/devicehub/agent

ADD . .

RUN glide install --skip-test

CMD ["/bin/sh"]

RUN glide install --skip-test && CC=arm-linux-gnueabihf-gcc GOOS=linux GOARCH=arm GOARM=6 CGO_ENABLED=1 go build

FROM pierrezemb/gostatic as main

COPY --from=builder /go/src/github.com/gustavosbarreto/devicehub/agent/agent /srv/http/devicehub-agent-arm
