# docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

FROM arm32v6/golang:alpine

RUN apk add --update git ca-certificates util-linux build-base bash && \
    go get -u github.com/Masterminds/glide

WORKDIR $GOPATH/src/github.com/shellhub-io/shellhub/agent

COPY glide.yaml glide.lock ./

RUN glide install

COPY . .

RUN glide -q install --skip-test && GOOS=linux GOARCH=arm go build -tags docker

FROM scratch

COPY --from=0 /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=0 /usr/bin/nsenter /usr/bin/
COPY --from=0 /lib/ld-musl-armhf.so.1 /lib/
COPY --from=0 /go/src/github.com/shellhub-io/shellhub/agent/agent /bin/agent

ENTRYPOINT ["/bin/agent"]
