#!/bin/sh

# This script is used to generate/update mock objects for testing

docker-compose -f docker-compose.yml -f docker-compose.dev.yml \
	       exec api mockery --name Store --dir ./store/ --output ./store/mocks --filename store.go

docker-compose -f docker-compose.yml -f docker-compose.dev.yml \
	       exec api mockery --name Service --dir ./services/ --output ./services/mocks --filename services.go

docker-compose -f docker-compose.yml -f docker-compose.dev.yml \
	       exec api mockery --name Backend --dir ../pkg/envs/ --output ../pkg/envs/mocks --filename envs.go

docker-compose -f docker-compose.yml -f docker-compose.dev.yml \
	       exec api mockery --name Clock --dir ../pkg/clock/ --output ../pkg/clock/mocks --filename clock.go

docker-compose -f docker-compose.yml -f docker-compose.dev.yml \
	       exec api mockery --name Uuid --dir ../pkg/uuid/ --output ../pkg/uuid/mocks --filename uuid.go
