#!/bin/bash

usage() {
    cat <<EOF
Run operations on OpenAPI service.
Usage:
    $0 <command>
Commands:
    generate  Run generation of all OpenAPI from instances
Options:
    --help  Display this help message
EOF
    exit 1
}

generate() {
    option=$1
    
    case $option in
        -h|--help)
            echo "Usage: $0 generate"
            echo "Generate a typescript from the OpenAPI spec"
            return
            ;;
    esac

    ./bin/docker-compose \
        exec new-ui \
        openapi-generator-cli generate \
            --skip-validate-spec \
            -i http://openapi:8080/openapi.json \
            -g typescript-axios \
            -o /src/src/api/client
}

main() {
    command=$1
    case $command in
        generate)
            shift
            $command $@
            exit $?
            ;;
        -h|--help)
            usage
            return
            ;;
        *)
            echo "$command is not a valid command"
            usage
            exit 1
    esac
}

main $@