#!/bin/sh

set -e

check_bin() {
    local cmd=$1

    if ! command -v "$cmd" &> /dev/null
    then
        echo "$cmd could not be found"
        exit 127
    fi
}

SHELLHUB_PATH=$(dirname $(dirname "$(realpath "$0")"))

SHELLHUB_DOMAIN=$(
    cd "$SHELLHUB_PATH"
    . ./.env
    [ ! -f .env.override ] || . ./.env.override
    printf '%s' "$SHELLHUB_DOMAIN"
)
SHELLHUB_URL="http://$SHELLHUB_DOMAIN"
