package storetest

import "testing"

// TestFunc is a store test as Groups names it: a method expression on Suite.
type TestFunc func(*Suite, *testing.T)

// Group is a set of store tests that share one freshly migrated database.
type Group struct {
	Name  string
	Tests []TestFunc
}

// Groups declares every store test and the database it runs against. Every test method on Suite
// appears in exactly one group, which TestEveryStoreTestBelongsToExactlyOneGroup enforces.
var Groups = []Group{
	{Name: "UserStore", Tests: []TestFunc{
		(*Suite).TestUserList,
		(*Suite).TestUserResolve,
		(*Suite).TestUserCreate,
		(*Suite).TestUserCreatePasswordRoundTrip,
		(*Suite).TestUserCreateDuplicate,
		(*Suite).TestUserUpdate,
		(*Suite).TestUserUpdatePreferredNamespace,
		(*Suite).TestUserUpdateDoesNotClobberPreferredNamespace,
		(*Suite).TestUserDelete,
		(*Suite).TestUserGetInfo,
		(*Suite).TestUserConflictsRemoved,
	}},
	{Name: "NamespaceStore", Tests: []TestFunc{
		(*Suite).TestNamespaceList,
		(*Suite).TestNamespaceResolve,
		(*Suite).TestNamespaceGetDeviceLimit,
		(*Suite).TestNamespaceGetPreferred,
		(*Suite).TestNamespaceCreate,
		(*Suite).TestNamespaceCreateDuplicate,
		(*Suite).TestNamespaceConflicts,
		(*Suite).TestNamespaceUpdate,
		(*Suite).TestNamespaceUpdateDoesNotClobberDeviceCounts,
		(*Suite).TestNamespaceIncrementDeviceCount,
		(*Suite).TestNamespaceSyncDeviceCounts,
		(*Suite).TestNamespaceDelete,
		(*Suite).TestNamespaceDeleteMany,
	}},
	{Name: "DeviceStore", Tests: []TestFunc{
		(*Suite).TestDeviceList,
		(*Suite).TestDeviceResolve,
		(*Suite).TestDeviceCreate,
		(*Suite).TestDeviceConflicts,
		(*Suite).TestDeviceUpdate,
		(*Suite).TestDeviceUpdateDoesNotClobberCustomFields,
		(*Suite).TestDeviceUpdateDoesNotClobberHeartbeat,
		(*Suite).TestDeviceHeartbeat,
		(*Suite).TestDeviceOffline,
		(*Suite).TestDeviceDelete,
		(*Suite).TestDeviceDeleteMany,
	}},
	{Name: "SessionStore", Tests: []TestFunc{
		(*Suite).TestSessionList,
		(*Suite).TestSessionResolve,
		(*Suite).TestSessionCreate,
		(*Suite).TestSessionUpdateDeviceUID,
		(*Suite).TestSessionUpdate,
		(*Suite).TestActiveSessionDelete,
		(*Suite).TestActiveSessionResolve,
		(*Suite).TestActiveSessionUpdate,
		(*Suite).TestActiveSessionUpdatePreservesCreatedAt,
		(*Suite).TestSessionEventsCreate,
		(*Suite).TestSessionEventsList,
		(*Suite).TestSessionEventsDelete,
		(*Suite).TestSessionCleanup,
	}},
	{Name: "TagStore", Tests: []TestFunc{
		(*Suite).TestTagCreate,
		(*Suite).TestTagConflicts,
		(*Suite).TestTagList,
		(*Suite).TestTagResolve,
		(*Suite).TestTagUpdate,
		(*Suite).TestTagPushToTarget,
		(*Suite).TestTagPullFromTarget,
		(*Suite).TestTagDelete,
	}},
	{Name: "APIKeyStore", Tests: []TestFunc{
		(*Suite).TestAPIKeyCreate,
		(*Suite).TestAPIKeyConflicts,
		(*Suite).TestAPIKeyResolve,
		(*Suite).TestAPIKeyList,
		(*Suite).TestAPIKeyUpdate,
		(*Suite).TestAPIKeyDelete,
		(*Suite).TestAPIKeyDeleteAllByCreator,
	}},
	{Name: "InstanceAPIKeyStore", Tests: []TestFunc{
		(*Suite).TestInstanceAPIKeyCreate,
		(*Suite).TestInstanceAPIKeyResolve,
		(*Suite).TestInstanceAPIKeyList,
		(*Suite).TestInstanceAPIKeyDelete,
	}},
	{Name: "InstallKeyStore", Tests: []TestFunc{
		(*Suite).TestInstallKeyModeRoundTrip,
		(*Suite).TestInstallKeyEventCreate,
		(*Suite).TestInstallKeyEventList,
	}},
	{Name: "PublicKeyStore", Tests: []TestFunc{
		(*Suite).TestPublicKeyResolve,
		(*Suite).TestPublicKeyList,
		(*Suite).TestPublicKeyCreate,
		(*Suite).TestPublicKeyUpdate,
		(*Suite).TestPublicKeyDelete,
	}},
	{Name: "StatsStore", Tests: []TestFunc{
		(*Suite).TestGetStats,
		(*Suite).TestGetStatsOnlineBoundary,
		(*Suite).TestCountRegisteredDevices,
	}},
	{Name: "PrivateKeyStore", Tests: []TestFunc{
		(*Suite).TestPrivateKeyCreate,
		(*Suite).TestPrivateKeyGet,
	}},
	{Name: "MemberStore", Tests: []TestFunc{
		(*Suite).TestNamespaceCreateMembership,
		(*Suite).TestNamespaceUpdateMembership,
		(*Suite).TestNamespaceDeleteMembership,
	}},
	{Name: "MembershipInvitationStore", Tests: []TestFunc{
		(*Suite).TestMembershipInvitationCreate,
		(*Suite).TestMembershipInvitationResolve,
		(*Suite).TestMembershipInvitationResolveBySig,
		(*Suite).TestMembershipInvitationUpdate,
		(*Suite).TestMembershipInvitationDelete,
		(*Suite).TestUserMembershipInvitationList,
		(*Suite).TestNamespaceMembershipInvitationList,
		(*Suite).TestNamespaceMembershipInvitationListWithStatusFilter,
	}},
	{Name: "UserInvitationStore", Tests: []TestFunc{
		(*Suite).TestUserInvitationsUpsert,
		(*Suite).TestUserInvitationGet,
		(*Suite).TestUserInvitationUpdate,
		(*Suite).TestUserInvitationUpdateDoesNotClobberInvitations,
	}},
	{Name: "SystemStore", Tests: []TestFunc{
		(*Suite).TestSystemGetDefault,
		(*Suite).TestSystemGet,
		(*Suite).TestSystemSet,
	}},
	{Name: "TransactionStore", Tests: []TestFunc{
		(*Suite).TestWithTransaction,
	}},
	{Name: "ScopeIsolation", Tests: []TestFunc{
		(*Suite).TestScopeIsolationDeviceResolve,
		(*Suite).TestScopeIsolationDeviceList,
		(*Suite).TestScopeIsolationDeviceConflicts,
		(*Suite).TestScopeIsolationSessionResolve,
		(*Suite).TestScopeIsolationSessionList,
		(*Suite).TestScopeIsolationTagResolve,
		(*Suite).TestScopeIsolationTagList,
		(*Suite).TestScopeIsolationTagConflicts,
		(*Suite).TestScopeIsolationInstallKeyResolve,
		(*Suite).TestScopeIsolationInstallKeyList,
		(*Suite).TestScopeIsolationInstallKeyConflicts,
		(*Suite).TestScopeIsolationInstallKeyResolveSystem,
		(*Suite).TestScopeIsolationInstallKeyResolveSystemPairing,
		(*Suite).TestScopeIsolationInstallKeyEventList,
		(*Suite).TestScopeIsolationInstallKeyEventStampDecision,
		(*Suite).TestScopeIsolationAPIKeyResolve,
		(*Suite).TestScopeIsolationAPIKeyList,
		(*Suite).TestScopeIsolationAPIKeyConflicts,
		(*Suite).TestScopeIsolationPublicKeyResolve,
		(*Suite).TestScopeIsolationPublicKeyList,
		(*Suite).TestScopeIsolationNamespaceGetMembers,
		(*Suite).TestScopeIsolationNamespaceIncrementDeviceCount,
		(*Suite).TestScopeIsolationMembershipWrites,
		(*Suite).TestScopeIsolationMembershipInvitationResolve,
		(*Suite).TestScopeIsolationNamespaceMembershipInvitationList,
		(*Suite).TestScopeIsolationGetStats,
		(*Suite).TestScopeIsolationCountRegisteredDevices,
		(*Suite).TestScopeIsolationAccessPolicyList,
		(*Suite).TestScopeIsolationAccessPolicyResolve,
		(*Suite).TestScopeIsolationSSHIdentityList,
		(*Suite).TestScopeIsolationSSHIdentityResolve,
		(*Suite).TestScopeRejectsUnconstructedScope,
	}},
}
