server {
    listen 8080;

    location /healthcheck {
        access_log off;
        return 200 "OK";
        add_header Content-Type text/plain;
    }

    location /v1/ {
        alias /usr/share/nginx/html/;
        index index.html index.htm;
        try_files $uri $uri/ /v1/index.html;
    }

    location ^~ /v1/admin/ {
        alias /usr/share/nginx/html/admin/;
        try_files $uri $uri/ /v1/admin/index.html;
    }

    error_page 500 502 503 504 /50x.html;

    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
