server {
    listen 8080;

    location /healthcheck {
        access_log off;
        return 200 "OK";
        add_header Content-Type text/plain;
    }

    location / {
        root /usr/share/nginx/html/ui;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
