root = "../../"
tmp_dir = "/tmp/air"

[build]
cmd = "go build -o /tmp/air/main github.com/shellhub-io/shellhub/api"
bin = "/tmp/air/main"
args_bin = ["server"]
exclude_regex = ["_test.go"]
include_dir = ["shellhub/api", "shellhub/openapi", "cloud"]
include_ext = ["go", "tpl", "tmpl", "html", "yaml", "yml", "json"]
