package main_test

// mocks_generate_test.go validates that all mock files declared in .mockery.yaml
// have been regenerated with mockery v3 and conform to the expected naming conventions.
//
// Verification criteria:
//  1. No "^type Mock" prefix in any generated struct.
//  2. pkg/uuid/mocks/uuid.go contains "^type Uuid struct".
//  3. pkg/geoip/mocks/Locator.go contains "^type Locator struct".
//  4. Wrong sibling files (api/services/mocks/service.go, pkg/hash/mocks/hasher.go) are absent.
//  5. Mock headers reference v3 (no "v2." in the first header line).
//  6. No "//go:build" tag in generated files.

import (
	"bufio"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// repoRoot returns the absolute path to the shellhub repository root by
// walking upward from the test file's directory until go.mod is found.
func repoRoot(t *testing.T) string {
	t.Helper()
	// The test is in api/, so the repo root is one level up.
	dir, err := filepath.Abs("..")
	require.NoError(t, err)

	return dir
}

// mockFiles returns the canonical list of generated mock files relative to
// the repository root, as declared in api/.mockery.yaml.
func mockFiles() []string {
	return []string{
		"pkg/cache/mocks/cache.go",
		"api/store/mocks/cache.go",
		"pkg/clock/mocks/clock.go",
		"pkg/envs/mocks/envs.go",
		"pkg/geoip/mocks/Locator.go",
		"pkg/hash/mocks/hash.go",
		"pkg/uuid/mocks/uuid.go",
		"pkg/websocket/mocks/conn.go",
		"pkg/websocket/mocks/upgrader.go",
		"pkg/worker/mocks/client.go",
		"pkg/worker/mocks/server.go",
		"pkg/api/client/mocks/client.go",
		"pkg/api/client/reverser/mocks/reverser.go",
		"pkg/api/internalclient/mocks/internalclient.go",
		"api/services/mocks/services.go",
		"api/services/mocks/license_evaluator.go",
		"api/store/mocks/store.go",
		"api/store/mocks/query_options.go",
	}
}

// readLines returns all lines of a file.
func readLines(t *testing.T, path string) []string {
	t.Helper()

	f, err := os.Open(path) //nolint:gosec
	require.NoError(t, err, "open %s", path)

	defer f.Close() //nolint:errcheck

	var lines []string
	sc := bufio.NewScanner(f)

	for sc.Scan() {
		lines = append(lines, sc.Text())
	}

	require.NoError(t, sc.Err())

	return lines
}

// TestMocksV3_FilesExist ensures every declared mock file exists.
func TestMocksV3_FilesExist(t *testing.T) {
	root := repoRoot(t)
	for _, rel := range mockFiles() {
		abs := filepath.Join(root, rel)
		_, err := os.Stat(abs)
		assert.NoError(t, err, "mock file should exist: %s", rel)
	}
}

// TestMocksV3_HeaderReferencesV3 verifies that no mock file has a "v2." version
// string in its generated header line.
func TestMocksV3_HeaderReferencesV3(t *testing.T) {
	root := repoRoot(t)
	v2Re := regexp.MustCompile(`mockery v2\.`)

	for _, rel := range mockFiles() {
		abs := filepath.Join(root, rel)
		lines := readLines(t, abs)
		require.NotEmpty(t, lines, "mock file should not be empty: %s", rel)

		// The first line is the generated header.
		firstLine := lines[0]
		assert.False(t, v2Re.MatchString(firstLine),
			"mock file %s still has a v2 header: %q", rel, firstLine)
	}
}

// TestMocksV3_NoMockPrefix verifies that no generated file declares a struct
// whose name begins with "Mock" (the v2 naming convention).
func TestMocksV3_NoMockPrefix(t *testing.T) {
	root := repoRoot(t)
	mockPrefixRe := regexp.MustCompile(`^type Mock`)

	for _, rel := range mockFiles() {
		abs := filepath.Join(root, rel)
		lines := readLines(t, abs)

		for _, line := range lines {
			assert.False(t, mockPrefixRe.MatchString(line),
				"mock file %s contains a v2 'Mock'-prefixed type: %q", rel, line)
		}
	}
}

// TestMocksV3_UuidStructName verifies that pkg/uuid/mocks/uuid.go uses "Uuid"
// (not "MockUUID" or "UUID") as the struct name.
func TestMocksV3_UuidStructName(t *testing.T) {
	root := repoRoot(t)
	abs := filepath.Join(root, "pkg/uuid/mocks/uuid.go")
	lines := readLines(t, abs)

	found := false

	for _, line := range lines {
		if strings.HasPrefix(line, "type Uuid struct") {
			found = true

			break
		}
	}

	assert.True(t, found, "pkg/uuid/mocks/uuid.go must contain 'type Uuid struct'")
}

// TestMocksV3_LocatorStructName verifies that pkg/geoip/mocks/Locator.go uses
// "Locator" as the struct name.
func TestMocksV3_LocatorStructName(t *testing.T) {
	root := repoRoot(t)
	abs := filepath.Join(root, "pkg/geoip/mocks/Locator.go")
	lines := readLines(t, abs)

	found := false

	for _, line := range lines {
		if strings.HasPrefix(line, "type Locator struct") {
			found = true

			break
		}
	}

	assert.True(t, found, "pkg/geoip/mocks/Locator.go must contain 'type Locator struct'")
}

// TestMocksV3_WrongSiblingFilesAbsent verifies that incorrectly-named mock files
// that would be generated by a misconfigured v2 run are absent.
func TestMocksV3_WrongSiblingFilesAbsent(t *testing.T) {
	root := repoRoot(t)

	wrongFiles := []string{
		"api/services/mocks/service.go",
		"pkg/hash/mocks/hasher.go",
	}

	for _, rel := range wrongFiles {
		abs := filepath.Join(root, rel)
		_, err := os.Stat(abs)
		assert.True(t, os.IsNotExist(err), "wrong sibling file should not exist: %s", rel)
	}
}

// TestMocksV3_NoBuildTag verifies that no generated mock file contains a
// //go:build constraint (mockery v3 does not emit build tags by default).
func TestMocksV3_NoBuildTag(t *testing.T) {
	root := repoRoot(t)
	buildTagRe := regexp.MustCompile(`^//go:build`)

	for _, rel := range mockFiles() {
		abs := filepath.Join(root, rel)
		lines := readLines(t, abs)

		for _, line := range lines {
			assert.False(t, buildTagRe.MatchString(line),
				"mock file %s must not contain a //go:build tag: %q", rel, line)
		}
	}
}
